name: hershot
services:
  postgres:
    image: postgres:16
    container_name: hershot-postgres
    environment:
      POSTGRES_USER: hershot
      POSTGRES_PASSWORD: hershot
      POSTGRES_DB: hershot
    ports:
      - "5432:5432"
    volumes:
      - hershot_postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: hershot-redis
    ports:
      - "6379:6379"

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: hershot-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "512M"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: hershot-dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - hershot_dynamodb_data:/home/dynamodblocal/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hershot-pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hershot.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  hershot_postgres_data:
  hershot_dynamodb_data: