package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	generated1 "github.com/wangly7/hershot/services/graphql-gateway/internal/graph/generated"
	"github.com/wangly7/hershot/services/graphql-gateway/internal/graph/model"
)

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context) ([]*model.Team, error) {
	teams, err := r.LeagueClient.ListTeams(ctx)
	if err != nil {
		return nil, fmt.Errorf("list teams: %w", err)
	}

	result := make([]*model.Team, 0, len(teams))

	for _, currentTeam := range teams {
		result = append(result, &model.Team{
			ID:           currentTeam.ID,
			Name:         currentTeam.Name,
			City:         currentTeam.City,
			Abbreviation: currentTeam.Abbreviation,
		})
	}

	return result, nil
	// panic(fmt.Errorf("not implemented: Teams - teams"))
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, id string) (*model.Team, error) {
	team, err := r.LeagueClient.GetTeam(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("list teams: %w", err)
	}

	return &model.Team{
		ID:           team.ID,
		Name:         team.Name,
		City:         team.City,
		Abbreviation: team.Abbreviation,
	}, nil
	// panic(fmt.Errorf("not implemented: Team - team"))
}

// Query returns generated1.QueryResolver implementation.
func (r *Resolver) Query() generated1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
